export interface Property {
  id: string
  title: string
  address: string
  suburb: string
  city: string
  region: string
  type: "apartment" | "house" | "townhouse" | "unit"
  listingType: "rent" | "sale"
  price: number
  priceDisplay: string
  bedrooms: number
  bathrooms: number
  parking: number
  landArea?: number
  floorArea?: number
  description: string
  features: string[]
  images: string[]
  availableFrom?: string
  furnished?: boolean
  petsAllowed?: boolean
  agent: {
    name: string
    phone: string
    email: string
  }
}

export const properties: Property[] = [
  {
    id: "45002441",
    title: "Modern Apartment in Stonefields",
    address: "G01/1 Percy Winstone Lane",
    suburb: "Stonefields",
    city: "Auckland City",
    region: "Auckland",
    type: "apartment",
    listingType: "rent",
    price: 650,
    priceDisplay: "$650 per week",
    bedrooms: 2,
    bathrooms: 2,
    parking: 1,
    floorArea: 85,
    description:
      "Stunning ground floor apartment in the heart of Stonefields. This modern home features open-plan living, quality finishes throughout, and a private courtyard. Walking distance to shops, cafes, and public transport.",
    features: [
      "Open-plan living and dining",
      "Modern kitchen with stone benchtops",
      "Master bedroom with ensuite",
      "Private courtyard",
      "Heat pump",
      "Internal access garage",
      "Security building",
    ],
    images: ["/modern-apartment-living-room.png", "/modern-kitchen-stone-benchtops.jpg", "/apartment-bedroom-ensuite.jpg"],
    availableFrom: "Immediately",
    furnished: false,
    petsAllowed: false,
    agent: {
      name: "Sarah Mitchell",
      phone: "021 456 7890",
      email: "sarah.mitchell@barfoot.co.nz",
    },
  },
  {
    id: "45002442",
    title: "Spacious Family Home in Mission Bay",
    address: "42 Tamaki Drive",
    suburb: "Mission Bay",
    city: "Auckland City",
    region: "Auckland",
    type: "house",
    listingType: "sale",
    price: 2850000,
    priceDisplay: "$2,850,000",
    bedrooms: 4,
    bathrooms: 3,
    parking: 2,
    landArea: 650,
    floorArea: 280,
    description:
      "Exceptional family home with stunning sea views. This beautifully renovated property offers spacious living areas, multiple outdoor entertaining spaces, and is just steps from the beach.",
    features: [
      "Sea views",
      "Renovated kitchen",
      "Multiple living areas",
      "Master suite with walk-in wardrobe",
      "Outdoor entertaining deck",
      "Double garage",
      "Swimming pool",
      "Landscaped gardens",
    ],
    images: ["/luxury-home-exterior-sea-view.jpg", "/modern-kitchen-island-marble.jpg", "/master-bedroom-ocean-view.jpg"],
    agent: {
      name: "David Thompson",
      phone: "021 234 5678",
      email: "david.thompson@barfoot.co.nz",
    },
  },
  {
    id: "45002443",
    title: "Contemporary Townhouse in Ponsonby",
    address: "15A Richmond Road",
    suburb: "Ponsonby",
    city: "Auckland City",
    region: "Auckland",
    type: "townhouse",
    listingType: "rent",
    price: 950,
    priceDisplay: "$950 per week",
    bedrooms: 3,
    bathrooms: 2,
    parking: 2,
    floorArea: 165,
    description:
      "Brand new townhouse in sought-after Ponsonby location. High-spec finishes, three levels of living, and walking distance to cafes, restaurants, and city transport.",
    features: [
      "Three levels",
      "High-spec kitchen appliances",
      "Heat pump and double glazing",
      "Master with ensuite and balcony",
      "Private courtyard",
      "Double internal garage",
      "Low maintenance",
    ],
    images: ["/modern-townhouse-exterior.png", "/contemporary-kitchen-black-fixtures.jpg", "/townhouse-bedroom-balcony.jpg"],
    availableFrom: "1st March",
    furnished: false,
    petsAllowed: true,
    agent: {
      name: "Emma Wilson",
      phone: "021 345 6789",
      email: "emma.wilson@barfoot.co.nz",
    },
  },
  {
    id: "45002444",
    title: "Waterfront Apartment in Takapuna",
    address: "Unit 501/23 The Strand",
    suburb: "Takapuna",
    city: "North Shore",
    region: "Auckland",
    type: "apartment",
    listingType: "sale",
    price: 1650000,
    priceDisplay: "$1,650,000",
    bedrooms: 2,
    bathrooms: 2,
    parking: 2,
    floorArea: 120,
    description:
      "Luxurious waterfront apartment with panoramic views of Rangitoto Island. Premium finishes, resort-style amenities, and steps to Takapuna Beach.",
    features: [
      "Panoramic sea views",
      "Premium kitchen with Miele appliances",
      "Floor-to-ceiling windows",
      "Large balcony",
      "Building pool and gym",
      "Secure parking for two",
      "Concierge service",
    ],
    images: ["/luxury-apartment-ocean-view-balcony.jpg", "/high-end-kitchen-miele-appliances.jpg", "/luxury-apartment-bedroom-views.jpg"],
    agent: {
      name: "Michael Chen",
      phone: "021 567 8901",
      email: "michael.chen@barfoot.co.nz",
    },
  },
  {
    id: "45002445",
    title: "Character Villa in Grey Lynn",
    address: "78 Surrey Crescent",
    suburb: "Grey Lynn",
    city: "Auckland City",
    region: "Auckland",
    type: "house",
    listingType: "rent",
    price: 850,
    priceDisplay: "$850 per week",
    bedrooms: 3,
    bathrooms: 2,
    parking: 1,
    landArea: 450,
    floorArea: 180,
    description:
      "Charming renovated villa with original features and modern comforts. Sunny north-facing garden, spacious rooms, and close to parks and cafes.",
    features: [
      "Original villa features",
      "Polished wooden floors",
      "Modern bathroom and kitchen",
      "North-facing garden",
      "Separate laundry",
      "Off-street parking",
      "Storage shed",
    ],
    images: ["/renovated-villa-exterior-garden.jpg", "/villa-interior-wooden-floors.jpg", "/character-home-kitchen.jpg"],
    availableFrom: "15th March",
    furnished: false,
    petsAllowed: true,
    agent: {
      name: "Lisa Anderson",
      phone: "021 678 9012",
      email: "lisa.anderson@barfoot.co.nz",
    },
  },
  {
    id: "45002446",
    title: "Executive Home in Remuera",
    address: "156 Orakei Road",
    suburb: "Remuera",
    city: "Auckland City",
    region: "Auckland",
    type: "house",
    listingType: "sale",
    price: 4250000,
    priceDisplay: "$4,250,000",
    bedrooms: 5,
    bathrooms: 4,
    parking: 3,
    landArea: 1200,
    floorArea: 450,
    description:
      "Stunning executive residence on premium Remuera site. Architecturally designed with luxury finishes, multiple living zones, pool, and beautifully landscaped grounds.",
    features: [
      "Architecturally designed",
      "High-end imported fixtures",
      "Wine cellar",
      "Home theatre",
      "Heated swimming pool and spa",
      "Triple garage with workshop",
      "Landscaped gardens",
      "Security system",
    ],
    images: ["/luxury-mansion-exterior-pool.jpg", "/designer-kitchen-marble-waterfall-island.jpg", "/executive-home-living-room.jpg"],
    agent: {
      name: "James Robertson",
      phone: "021 789 0123",
      email: "james.robertson@barfoot.co.nz",
    },
  },
  {
    id: "45002447",
    title: "Modern Unit in Mt Wellington",
    address: "Unit 12/45 Springs Road",
    suburb: "Mt Wellington",
    city: "Auckland City",
    region: "Auckland",
    type: "unit",
    listingType: "rent",
    price: 550,
    priceDisplay: "$550 per week",
    bedrooms: 2,
    bathrooms: 1,
    parking: 1,
    floorArea: 75,
    description:
      "Well-maintained unit in convenient location. Easy motorway access, near Sylvia Park shopping centre, and close to public transport.",
    features: ["Open-plan living", "Good storage", "Heat pump", "Single carport", "Shared courtyard", "Easy care"],
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    availableFrom: "Immediately",
    furnished: false,
    petsAllowed: false,
    agent: {
      name: "Rachel Park",
      phone: "021 890 1234",
      email: "rachel.park@barfoot.co.nz",
    },
  },
  {
    id: "45002448",
    title: "Beachside House in Milford",
    address: "89 The Esplanade",
    suburb: "Milford",
    city: "North Shore",
    region: "Auckland",
    type: "house",
    listingType: "sale",
    price: 3150000,
    priceDisplay: "$3,150,000",
    bedrooms: 4,
    bathrooms: 3,
    parking: 2,
    landArea: 800,
    floorArea: 320,
    description:
      "Spectacular beachfront property with direct access to Milford Beach. Renovated to perfection with seamless indoor-outdoor flow and breathtaking coastal views.",
    features: [
      "Beachfront position",
      "Panoramic sea views",
      "Gourmet kitchen",
      "Multiple entertaining areas",
      "Master suite with spa bath",
      "Double garage",
      "Fully fenced section",
    ],
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    agent: {
      name: "Sophie Turner",
      phone: "021 901 2345",
      email: "sophie.turner@barfoot.co.nz",
    },
  },
  {
    id: "45002449",
    title: "City Apartment in Parnell",
    address: "Apt 304/88 The Strand",
    suburb: "Parnell",
    city: "Auckland City",
    region: "Auckland",
    type: "apartment",
    listingType: "rent",
    price: 750,
    priceDisplay: "$750 per week",
    bedrooms: 2,
    bathrooms: 2,
    parking: 1,
    floorArea: 95,
    description:
      "Sophisticated apartment in the heart of Parnell. Walking distance to cafes, restaurants, and the city. Building amenities include gym and pool.",
    features: [
      "City views",
      "Stone kitchen benchtops",
      "Built-in wardrobes",
      "Balcony",
      "Building gym and pool",
      "Secure parking",
      "Storage locker",
    ],
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    availableFrom: "1st April",
    furnished: false,
    petsAllowed: false,
    agent: {
      name: "Tom Bradley",
      phone: "021 012 3456",
      email: "tom.bradley@barfoot.co.nz",
    },
  },
  {
    id: "45002450",
    title: "Family Home in Albany",
    address: "23 Oteha Valley Road",
    suburb: "Albany",
    city: "North Shore",
    region: "Auckland",
    type: "house",
    listingType: "sale",
    price: 1850000,
    priceDisplay: "$1,850,000",
    bedrooms: 4,
    bathrooms: 2,
    parking: 2,
    landArea: 700,
    floorArea: 240,
    description:
      "Modern family home in popular Albany location. Close to Westfield Albany, parks, and excellent schools. Perfect for growing families.",
    features: [
      "Four double bedrooms",
      "Open-plan family living",
      "Modern kitchen with scullery",
      "Covered outdoor area",
      "Heat pump and HRV system",
      "Double garage",
      "Fully fenced yard",
    ],
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    agent: {
      name: "Karen White",
      phone: "021 123 4567",
      email: "karen.white@barfoot.co.nz",
    },
  },
  {
    id: "45002451",
    title: "Studio Apartment in Newmarket",
    address: "Level 6/277 Broadway",
    suburb: "Newmarket",
    city: "Auckland City",
    region: "Auckland",
    type: "apartment",
    listingType: "rent",
    price: 450,
    priceDisplay: "$450 per week",
    bedrooms: 1,
    bathrooms: 1,
    parking: 0,
    floorArea: 42,
    description:
      "Compact studio in prime Newmarket location. Perfect for young professionals. Walking distance to shops, cafes, and public transport.",
    features: ["Open-plan living", "Modern bathroom", "Good storage", "Shared laundry", "Building security"],
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    availableFrom: "Immediately",
    furnished: true,
    petsAllowed: false,
    agent: {
      name: "Alex Kim",
      phone: "021 234 5670",
      email: "alex.kim@barfoot.co.nz",
    },
  },
  {
    id: "45002452",
    title: "Luxury Penthouse in Viaduct",
    address: "Penthouse 1/155 Quay Street",
    suburb: "Auckland Central",
    city: "Auckland City",
    region: "Auckland",
    type: "apartment",
    listingType: "sale",
    price: 5250000,
    priceDisplay: "$5,250,000",
    bedrooms: 3,
    bathrooms: 3,
    parking: 3,
    floorArea: 280,
    description:
      "Ultimate luxury penthouse in prestigious Viaduct location. Panoramic harbour views, world-class finishes, and exclusive building amenities.",
    features: [
      "360-degree harbour views",
      "Italian marble throughout",
      "Chef's kitchen with butler's pantry",
      "Private lift access",
      "Multiple terraces",
      "Climate-controlled wine cellar",
      "Building concierge",
      "Three secure car parks",
    ],
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    agent: {
      name: "Victoria Hamilton",
      phone: "021 345 6701",
      email: "victoria.hamilton@barfoot.co.nz",
    },
  },
  {
    id: "45002453",
    title: "Townhouse in Hobsonville Point",
    address: "Unit 8/45 Catalina Crescent",
    suburb: "Hobsonville",
    city: "Waitakere",
    region: "Auckland",
    type: "townhouse",
    listingType: "rent",
    price: 780,
    priceDisplay: "$780 per week",
    bedrooms: 3,
    bathrooms: 2,
    parking: 2,
    floorArea: 145,
    description:
      "Modern townhouse in vibrant Hobsonville Point community. Near waterfront, parks, and local shops. Great schools nearby.",
    features: [
      "Three good-sized bedrooms",
      "Open-plan living",
      "Modern kitchen",
      "Private courtyard",
      "Double glazing and insulation",
      "Internal garage",
      "Low maintenance",
    ],
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    availableFrom: "15th April",
    furnished: false,
    petsAllowed: false,
    agent: {
      name: "Daniel Foster",
      phone: "021 456 7012",
      email: "daniel.foster@barfoot.co.nz",
    },
  },
  {
    id: "45002454",
    title: "Heritage Home in Devonport",
    address: "34 Victoria Road",
    suburb: "Devonport",
    city: "North Shore",
    region: "Auckland",
    type: "house",
    listingType: "sale",
    price: 2650000,
    priceDisplay: "$2,650,000",
    bedrooms: 4,
    bathrooms: 2,
    parking: 2,
    landArea: 850,
    floorArea: 260,
    description:
      "Beautifully restored heritage villa in sought-after Devonport village. Blend of period charm and modern convenience, walking distance to ferry and beach.",
    features: [
      "Original villa features",
      "High stud ceilings",
      "Bay windows",
      "Modern kitchen and bathrooms",
      "Mature gardens",
      "Off-street parking",
      "Walk to ferry and shops",
    ],
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    agent: {
      name: "Patricia Moore",
      phone: "021 567 0123",
      email: "patricia.moore@barfoot.co.nz",
    },
  },
  {
    id: "45002455",
    title: "New Build in Flat Bush",
    address: "12 Ormiston Road",
    suburb: "Flat Bush",
    city: "Manukau",
    region: "Auckland",
    type: "house",
    listingType: "sale",
    price: 1250000,
    priceDisplay: "$1,250,000",
    bedrooms: 4,
    bathrooms: 2,
    parking: 2,
    landArea: 400,
    floorArea: 200,
    description:
      "Brand new family home in growing Flat Bush area. Modern design, quality construction, and close to Town Centre and schools.",
    features: [
      "Brand new construction",
      "Open-plan living",
      "Quality fixtures and fittings",
      "Heat pump",
      "Full insulation and double glazing",
      "Double garage",
      "Master with walk-in wardrobe",
      "10-year Master Build warranty",
    ],
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    agent: {
      name: "Steven Lee",
      phone: "021 678 0124",
      email: "steven.lee@barfoot.co.nz",
    },
  },
  {
    id: "45002456",
    title: "Cosy Unit in Sandringham",
    address: "Unit 3/98 Sandringham Road",
    suburb: "Sandringham",
    city: "Auckland City",
    region: "Auckland",
    type: "unit",
    listingType: "rent",
    price: 520,
    priceDisplay: "$520 per week",
    bedrooms: 2,
    bathrooms: 1,
    parking: 1,
    floorArea: 68,
    description:
      "Tidy unit in popular Sandringham. Easy access to city, shops, and public transport. Perfect for small family or couple.",
    features: [
      "Two bedrooms",
      "Combined living and dining",
      "Separate kitchen",
      "Shared laundry",
      "Single carport",
      "Small private courtyard",
    ],
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    availableFrom: "10th March",
    furnished: false,
    petsAllowed: false,
    agent: {
      name: "Jenny Martinez",
      phone: "021 789 0125",
      email: "jenny.martinez@barfoot.co.nz",
    },
  },
  {
    id: "45002457",
    title: "Lifestyle Property in Kumeu",
    address: "125 State Highway 16",
    suburb: "Kumeu",
    city: "Rodney",
    region: "Auckland",
    type: "house",
    listingType: "sale",
    price: 1950000,
    priceDisplay: "$1,950,000",
    bedrooms: 5,
    bathrooms: 3,
    parking: 4,
    landArea: 5000,
    floorArea: 340,
    description:
      "Stunning lifestyle property on 5000sqm. Spacious home with multiple living areas, large shed, and room for horses or hobbies. Rural living just 30 minutes from city.",
    features: [
      "5000sqm section",
      "Large family home",
      "Multiple living zones",
      "Modern kitchen",
      "Outdoor entertaining",
      "Large shed/workshop",
      "Paddocks and gardens",
      "Rural views",
    ],
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    agent: {
      name: "Mark Johnson",
      phone: "021 890 0126",
      email: "mark.johnson@barfoot.co.nz",
    },
  },
  {
    id: "45002458",
    title: "Waterfront Townhouse in Half Moon Bay",
    address: "Unit 5/78 Marina Drive",
    suburb: "Half Moon Bay",
    city: "Manukau",
    region: "Auckland",
    type: "townhouse",
    listingType: "sale",
    price: 1450000,
    priceDisplay: "$1,450,000",
    bedrooms: 3,
    bathrooms: 2,
    parking: 2,
    floorArea: 155,
    description:
      "Stunning waterfront townhouse with marina berth. Contemporary design, quality finishes, and boat mooring included. Coastal living at its best.",
    features: [
      "Waterfront position",
      "Marina berth included",
      "Water views",
      "Modern kitchen",
      "Three levels",
      "Master with ensuite",
      "Double garage",
      "Low maintenance",
    ],
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    agent: {
      name: "Amanda Roberts",
      phone: "021 901 0127",
      email: "amanda.roberts@barfoot.co.nz",
    },
  },
  {
    id: "45002459",
    title: "Garden Apartment in Epsom",
    address: "Ground Floor/56 Manukau Road",
    suburb: "Epsom",
    city: "Auckland City",
    region: "Auckland",
    type: "apartment",
    listingType: "rent",
    price: 680,
    priceDisplay: "$680 per week",
    bedrooms: 2,
    bathrooms: 1,
    parking: 1,
    floorArea: 82,
    description:
      "Quiet ground-floor apartment with private garden access. Great Epsom location near shops, cafes, and Grammar Zone schools.",
    features: [
      "Ground floor with garden access",
      "Two double bedrooms",
      "Open-plan living",
      "Modern bathroom",
      "Heat pump",
      "Single carpark",
      "Storage unit",
    ],
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    availableFrom: "1st May",
    furnished: false,
    petsAllowed: true,
    agent: {
      name: "Chris Wong",
      phone: "021 012 0128",
      email: "chris.wong@barfoot.co.nz",
    },
  },
  {
    id: "45002460",
    title: "Renovated Bungalow in Mt Eden",
    address: "67 Valley Road",
    suburb: "Mt Eden",
    city: "Auckland City",
    region: "Auckland",
    type: "house",
    listingType: "sale",
    price: 3450000,
    priceDisplay: "$3,450,000",
    bedrooms: 4,
    bathrooms: 3,
    parking: 2,
    landArea: 850,
    floorArea: 320,
    description:
      "Exquisitely renovated bungalow in prime Mt Eden location. Seamless blend of character charm and contemporary luxury. Walking distance to village.",
    features: [
      "Character bungalow",
      "High-end renovation",
      "Designer kitchen",
      "Luxury bathrooms",
      "Indoor-outdoor flow",
      "Landscaped gardens",
      "Off-street parking",
      "Walk to Mt Eden village",
    ],
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    agent: {
      name: "Rebecca Taylor",
      phone: "021 123 0129",
      email: "rebecca.taylor@barfoot.co.nz",
    },
  },
]

export function searchProperties(query: string, listingType: "rent" | "sale" | "all" = "all"): Property[] {
  const lowerQuery = query.toLowerCase().trim()

  if (!lowerQuery) {
    return listingType === "all" ? properties : properties.filter((p) => p.listingType === listingType)
  }

  return properties.filter((property) => {
    const matchesType = listingType === "all" || property.listingType === listingType
    const matchesQuery =
      property.suburb.toLowerCase().includes(lowerQuery) ||
      property.city.toLowerCase().includes(lowerQuery) ||
      property.region.toLowerCase().includes(lowerQuery) ||
      property.address.toLowerCase().includes(lowerQuery) ||
      property.title.toLowerCase().includes(lowerQuery) ||
      property.type.toLowerCase().includes(lowerQuery)

    return matchesType && matchesQuery
  })
}

export function getPropertyById(id: string): Property | undefined {
  return properties.find((p) => p.id === id)
}
